import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import { Header } from "./Components/Header/Header";
import { Footer } from "./Components/Footer/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" suppressHydrationWarning className="dark:bg-[--background]" >
      <body>
        <ThemeProvider attribute="class" > 
         <Header/>
    
          {children}

         <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
